#!/usr/bin/env -S uv run --script
# /// script
# dependencies = ["requests", "openmeteo-requests", "requests-cache", "retry-requests", "numpy", "pandas", "geopy"]
# ///

import openmeteo_requests
import pandas as pd
import requests_cache
from retry_requests import retry
from geopy.geocoders import Nominatim
import requests
import os
import json

# code generated by open-meteo.com, then modified

def get_location():
    response = requests.get("https://ipinfo.io")
    data = response.json()
    loc = data["loc"].split(",")
    return float(loc[0]), float(loc[1])


latitude, longitude = get_location()

geolocator = Nominatim(user_agent="idk")
location = geolocator.reverse(f"{latitude}, {longitude}")
print(location.address)
parsedLocation = str(location.address).split(",")
locationString = f"{parsedLocation[-5]}, {parsedLocation[-1]}" # {parsedLocation[-6]} ->  location in the city


cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

url = "https://api.open-meteo.com/v1/forecast"

params = {
	"latitude": latitude, 
	"longitude": longitude,
	"daily": ["weather_code", "temperature_2m_max", "temperature_2m_min"],
	"current": ["temperature_2m", "apparent_temperature", "precipitation", "rain", "weather_code"],
	"timezone": "Europe/Berlin",
    "forecast_days": 1
}

aggregated_data = {
    "location": locationString,
    "description": "",
    "icon": "",
    "temp": "",
    "feels": "",
    "rain": "",
    "precipitation": "",
    "high": "",
    "low": ""
}

responses = openmeteo.weather_api(url, params = params)

response = responses[0]
# print(f"Coordinates: {response.Latitude()}°N {response.Longitude()}°E")
# print(f"Elevation: {response.Elevation()} m asl")
# print(f"Timezone: {response.Timezone()}{response.TimezoneAbbreviation()}")
# print(f"Timezone difference to GMT+0: {response.UtcOffsetSeconds()}s")

current = response.Current()
current_temperature_2m = current.Variables(1).Value()
current_apparent_temperature = current.Variables(1).Value()
current_precipitation = current.Variables(2).Value()
current_rain = current.Variables(3).Value()
current_weather_code = current.Variables(4).Value()

WMO_CODES = {
    0: "Clear sky",
    1: "Mainly clear",
    2: "Partly cloudy",
    3: "Overcast",
    45: "Fog",
    48: "Depositing rime fog",
    51: "Light drizzle",
    53: "Moderate drizzle",
    55: "Dense drizzle",
    61: "Slight rain",
    63: "Moderate rain",
    65: "Heavy rain",
    71: "Slight snow fall",
    73: "Moderate snow fall",
    75: "Heavy snow fall",
    77: "Snow grains",
    80: "Slight rain showers",
    81: "Moderate rain showers",
    82: "Violent rain showers",
    85: "Slight snow showers",
    86: "Heavy snow showers",
    95: "Thunderstorm",
    96: "Thunderstorm with slight hail",
    99: "Thunderstorm with heavy hail",
}

WEATHER_ICONS = {
    0: "\uf00d", 1: "\uf002", 2: "\uf002", 3: "\uf013",
    4: "\uf062", 5: "\uf0b6", 6: "\uf063", 7: "\uf063", 8: "\uf063", 9: "\uf082",
    10: "\uf014", 11: "\uf014", 12: "\uf014", 13: "\uf016", 17: "\uf01e", 18: "\uf050", 19: "\uf056",
    20: "\uf01c", 21: "\uf019", 22: "\uf01b", 23: "\uf017", 24: "\uf017", 25: "\uf01a",
    30: "\uf082", 31: "\uf082", 32: "\uf082", 33: "\uf082", 34: "\uf082", 35: "\uf082",
    36: "\uf064", 37: "\uf064", 38: "\uf064", 39: "\uf064",
    40: "\uf014", 41: "\uf014", 42: "\uf014", 43: "\uf014", 44: "\uf014", 
    45: "\uf014", 46: "\uf014", 47: "\uf014", 48: "\uf014", 49: "\uf014",
    50: "\uf01c", 51: "\uf01c", 52: "\uf01c", 53: "\uf01c", 54: "\uf01c", 
    55: "\uf01c", 56: "\uf017", 57: "\uf017", 58: "\uf01c", 59: "\uf01c",
    60: "\uf019", 61: "\uf019", 62: "\uf019", 63: "\uf019", 64: "\uf019", 
    65: "\uf019", 66: "\uf017", 67: "\uf017", 68: "\uf017", 69: "\uf017",
    70: "\uf01b", 71: "\uf01b", 72: "\uf01b", 73: "\uf01b", 74: "\uf01b", 
    75: "\uf01b", 76: "\uf076", 77: "\uf01b", 78: "\uf01b", 79: "\uf017",
    80: "\uf01a", 81: "\uf01a", 82: "\uf01a", 83: "\uf01a", 84: "\uf01a", 
    85: "\uf076", 86: "\uf076", 87: "\uf015", 88: "\uf015", 89: "\uf015",
    90: "\uf01e", 91: "\uf01e", 92: "\uf01e", 93: "\uf01e", 94: "\uf01e", 
    95: "\uf01e", 96: "\uf01e", 97: "\uf01e", 98: "\uf01e", 99: "\uf01e",
}

print(int(current_weather_code))

try:
    aggregated_data["description"] = WMO_CODES[int(current_weather_code)]
except KeyError:
    aggregated_data["description"] = "No description"

print(current_apparent_temperature)

aggregated_data["icon"] = WEATHER_ICONS[int(current_weather_code)]
aggregated_data["temp"] = f"{str(current_temperature_2m).split('.')[0]}.{str(current_temperature_2m).split('.')[1][:2]}"
aggregated_data["feels"] = f"{str(current_apparent_temperature).split('.')[0]}.{str(current_apparent_temperature).split('.')[1][:2]}"
aggregated_data["rain"] = str(current_rain)
aggregated_data["precipitation"] = str(current_precipitation)


daily = response.Daily()
daily_weather_code = daily.Variables(0).ValuesAsNumpy()
daily_temperature_2m_max = daily.Variables(1).ValuesAsNumpy()
daily_temperature_2m_min = daily.Variables(2).ValuesAsNumpy()

daily_data = {"date": pd.date_range(
	start = pd.to_datetime(daily.Time() + response.UtcOffsetSeconds(), unit = "s", utc = True),
	end =  pd.to_datetime(daily.TimeEnd() + response.UtcOffsetSeconds(), unit = "s", utc = True),
	freq = pd.Timedelta(seconds = daily.Interval()),
	inclusive = "left"
)}

daily_data["temperature_2m_max"] = daily_temperature_2m_max
daily_data["temperature_2m_min"] = daily_temperature_2m_min


# daily_dataframe = pd.DataFrame(data = daily_data)
# print("\nDaily data\n", daily_dataframe)

print(str(daily_data['temperature_2m_max']))

aggregated_data["high"] = f"{str(daily_data['temperature_2m_max'][0]).split('.')[0]}.{str(daily_data['temperature_2m_max'][0]).split('.')[1][:2]}"
aggregated_data["low"] = f"{str(daily_data['temperature_2m_min'][0]).split('.')[0]}.{str(daily_data['temperature_2m_min'][0]).split('.')[1][:2]}"

json_data = json.dumps(aggregated_data, indent=4)

print("\nJson data: \n", json_data)

try:
    with open(os.path.expanduser("~/.cache/.weather_cache"), "w") as file:
        file.write(json_data)
except Exception as e:
    print("Something went wrong")
